CREATE TABLE product_images(
	id INT(12) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	productId INT(12) NOT NULL,
	path VARCHAR(255) NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP,
	FOREIGN KEY (productId) REFERENCES product(id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
)